version: '3'

services:
  book:
    build:
      context: ./Project/Project
    container_name: book
    command: python Project/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - sqlite3

  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
    ports:
      - "3306:3306"



#

